version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m unittest discover
          name: Test
      - run:
          command: |
            sudo pip install coverage
            coverage run --source .cli_tool -m unittest discover
          name: Coverage

workflows:
  main:
    jobs:
      - build-and-test
